# Copyright (c) 2020 The University of Manchester
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

name: "Install Python Package from Source"
inputs:
  preinstall:
    description: Whether to run the requirements.txt ahead of the main install
    required: false
    default: false
  requirements-path:
    description: The name of the requirements.txt
    required: false
    default: requirements.txt
  test-requirements:
    description: Whether to run the requirements-test.txt after the main install
    required: false
    default: true
  test-requirements-path:
    description: The name of the requirements-test.txt
    required: false
    default: requirements-test.txt
  mode:
    description: What mode to install in
    required: false
    default: develop
runs:
  using: composite
  steps: 
    - run: |
        if [ ${{ inputs.preinstall }} = "true" ]; then
          echo "::group::Doing dependency preinstall"
          pip install -r ${{ inputs.requirements-path }}
          code=$?
          echo "::endgroup::"
          exit $code
        fi
      shell: bash
    - run: exec python setup.py ${{ inputs.mode }}
      shell: bash
    - run: |
        if [ ${{ inputs.test-requirements }} = "true" ]; then
          echo "::group::Doing test-code install"
          pip install -r ${{ inputs.test-requirements-path }}
          code=$?
          echo "::endgroup::"
          exit $code
        fi
      shell: bash
