# Copyright (c) 2020 The University of Manchester
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

name: "Install Advanced Python Tools"
inputs:
  pylint-version:
    description: The version of pylint desired
    required: false
    default: < 2.5
  coverage:
    description: Whether to install tools for coverage checking
    required: false
    default: true
  coverage-version:
    description: The version of coverage desired
    required: false
    default: ">= 4.4, < 5.0"
runs:
  using: composite
  steps: 
  - run: |
      python -m pip install --upgrade pip setuptools wheel
      pip install flake8 "pylint $PYLINT_VERSION"
      if [ $DO_COVERAGE = "true" ]; then
        pip install "coverage $COVERAGE_VERSION" python-coveralls
      fi
    shell: bash
    env:
      PYLINT_VERSION: ${{ inputs.pylint-version }}
      DO_COVERAGE: ${{ inputs.coverage == 'true' }}
      COVERAGE_VERSION: ${{ inputs.coverage-version }}
