# Copyright (c) 2020 The University of Manchester
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

name: "Run Pylint"
description: |
  Runs pylint on a Python package. 
  Note that installing pylint in the environment before this action is up to the caller.
inputs:
  package:
    description: The name of the Python package (or packages) to analyse
    required: true
  disable:
    description: The messages/categories to disable
    required: false
    default: "R,C"
  jobs:
    description: The number of Python processes to use
    required: false
    default: 1
  rcfile:
    description: The name of the pylint rc file
    required: false
    default: .pylintrc
runs:
  using: composite
  steps: 
    - run: |
        pylint --output-format=colorized --disable=${{ inputs.disable }} \
          --persistent=no --jobs=${{ inputs.jobs }} --rcfile=${{ inputs.rcfile }} \
          ${{ inputs.package }} || exit $(($? & 35))
      # Note that there's special conditioning of the return code of pylint
      shell: bash
